### ISSUE TITLE
http://twittery.herokuapp.com/ Does not return response

### ISSUE THREAD

**Issue by pratikpparikh** [christianv/twittery#1]
Hi Dear Author,

```
 Your hosted service has stopped responding with tweets. Can you kindly look into this? 
```

Regards,
Pratik Parikh

**Comment by christianvuerings** [comment]
@pratikpparikh Thanks for using the service! Twitter changed their tweet selector so I've updated the code and herokuapp. Can you see whether it works for you?

http://twittery.herokuapp.com/denbuzze

**Comment by pratikpparikh** [comment]
Yes thanks so much
